return {
  -- Taking a break from Copilot
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   build = ":Copilot auth",
  --   event = "InsertEnter",
  --   opts = {
  --     suggestion = {
  --       enabled = true,
  --       auto_trigger = true,
  --       keymap = {
  --         accept = "<C-l>",
  --       },
  --     },
  --     panel = { enabled = false },
  --     filetypes = {
  --       markdown = false,
  --       yaml = true,
  --       text = false,
  --     },
  --   },
  -- },
}
